### ISSUE TITLE
Maven Central release?

### ISSUE THREAD

**Issue by toolforger** [Sleaker/jlibnoise#1]
Any plans to release this to Maven Central?

**Comment by toolforger** [comment]
I just stumbled upon `https://jitpack.io`. That may be much easier than Maven Central.

**Comment by Sleaker** [comment]
ah maybe, I wasn't publishing it at the moment due to being so small and easy to build.

**Comment by toolforger** [comment]
Version management becomes much easier. When people fork my project, they will see a jlibnoise subdirectory but won't know not what version it is, and which fixes it includes.

**Comment by Sleaker** [comment]
now available from https://jitpack.io/#Sleaker/jlibnoise/v1.0

**Comment by toolforger** [comment]
Thanks - better late than never :-)
