### ISSUE TITLE
(Not verified) Perlin may have a scaling error

### ISSUE THREAD

**Issue by toolforger** [Sleaker/jlibnoise#2]
I _think_ the Perlin generator adds multiple octaves, but does not account for how many octaves at what persistence factor are added. With a persistence of 0.5, I'd expect the noise values to approximate the +/- 2.0 range as more octaves are added.
Disclaimer: I haven't verified this, I found this bug in another libnoise port, just now checked your code and didn't find it would apply a scaling factor that integrates the persistence and the number of octaves.

**Comment by Sleaker** [comment]
Do you have the other port reference available and the classes/lines of code where you checked so I can look into this and how it differs from the official version?

**Comment by toolforger** [comment]
The statement that made my bug sense tingle is here:
https://github.com/Sleaker/jlibnoise/blob/master/src/main/java/net/jlibnoise/generator/Perlin.java#L341
`value` is incremented a parameter-dependent number of times, which should expand the range interval, yet no attempt is made to scale that back to [-1..1].
I don't know the original, so you are probably in a better position to identify the corresponding line in the original.
It's quite possible that this is a bug that has been present in the original.

**Comment by Sleaker** [comment]
Here's the source from libnoise 1.0.0:

```
for (int curOctave = 0; curOctave < m_octaveCount; curOctave++) {

// Make sure that these floating-point values have the same range as a 32-
// bit integer so that we can pass them to the coherent-noise functions.
nx = MakeInt32Range (x);
ny = MakeInt32Range (y);
nz = MakeInt32Range (z);

// Get the coherent-noise value from the input value and add it to the
// final result.
seed = (m_seed + curOctave) & 0xffffffff;
signal = GradientCoherentNoise3D (nx, ny, nz, seed, m_noiseQuality);
value += signal * curPersistence;

// Prepare the next octave.
x *= m_lacunarity;
y *= m_lacunarity;
z *= m_lacunarity;
curPersistence *= m_persistence;
}
```

looks the same to me, I'd say probably report it up to libnoise and see what he has to say about it.

Edit: I don't think octaves are supposed to bound the values back to -1,1. Octaves aren't a part of standard perlin generation in the first place, but I always thought they were additive when you did add them in.

**Comment by toolforger** [comment]
Sounds like a plan.

**Comment by toolforger** [comment]
Why the close?
Specifically, what did he say about it?

**Comment by Sleaker** [comment]
@toolforger - I didn't ask.  I closed because of my previous statement about not believing octaves are supposed to floor/ceil back to -1,1 range and the fact that it's the same in the upstream library so it's consistent across the port.

**Comment by toolforger** [comment]
Between octave addition and generator output, it's still not scaling back to -1..1 (I believe, I'm seeing values up to 1.3 with two octaves so I _guess_ it's wrong somewhere around here).

**Comment by Sleaker** [comment]
@toolforger - correct, that's what I just stated as intended, there's nothing wrong here.

**Comment by toolforger** [comment]
Well okay... if you think the Perlin module is okay... (I'm pretty sure it isn't but whatever)
